### ISSUE TITLE
Fields that don't directly inherit from django Field are broken

### ISSUE THREAD

**Issue by levic** [gregmuellegger/django-floppyforms#132] opened 2014-11-19 01:45 UTC
The definition for DateTimeField is

```python
class Field(forms.Field):
    widget = TextInput
    hidden_widget = HiddenInput

class DateTimeField(Field, forms.DateTimeField):
    widget = DateTimeInput
```

The problem is that django's DateTimeField overrides ```to_python()```.

Because ```floppyforms.Field``` is first in the inheritance hierarchy, the ```to_python()``` from ```djangoforms.Field``` wins over ```djangoforms.DateTimeField``` which means that you never end up with a submitted date value converted to a ```datetime``` object (and then validation fails)

I think ```floppyforms.Field``` should be a mixin and not inherit from anything

**Comment by gregmuellegger** [comment] 2015-03-02 09:55
I'm closing off this issue because I don't have enough information to reproduce. Please feel free to re-open it if you this still bugs you.

**Closed by gregmuellegger** 2015-03-02 09:55 UTC
Labels: Needs information
